name: build and deploy jekyll website
on: [push]
jobs:
  build:
    name: Generate website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        ref: master
    - name: Run jekyll
      uses: docker://faph/action-jekyll:1.5
    - name: Copy to one.com
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.ONE_SFTP_HOST }}
        ftp-username: ${{ secrets.ONE_SFTP_USER }}
        ftp-password: ${{ secrets.ONE_SFTP_PASSWORD }}
        local-dir: "/github/workspace/_site"
