name: build and deploy jekyll website
on: [push]
jobs:
  build:
    name: Generate website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        ref: master
    - name: Run jekyll
      uses: docker://faph/action-jekyll:1.5
    - name: Copy to one.com
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ONE_SSH_HOST }}
        username: ${{ secrets.ONE_SSH_USER }}
        password: ${{ secrets.ONE_SSH_PASSWORD }}
        source: "/github/workspace/_site"
        target: "/www/testscp"
        strip_components: 3
